name: Publish GitHub Action

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Configure Git user
        run: |
          git config --global user.email "olinyajames@gmail.com"
          git config --global user.name "James Olinya"

      - name: Bump version and create tag
        id: bump_version
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.bump_version.outputs.version }}
          name: Release ${{ steps.bump_version.outputs.version }}
          body: "Release of version ${{ steps.bump_version.outputs.version }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
